### ISSUE TITLE
Installation requirements missing

### ISSUE THREAD

**Issue by Ge0rges** [MicrobialDarkMatter/nanomotif#76]
Hello, 

Just a heads up that when following the installation instructions one obtains the following error:
```
/Accounts/gkanaan/.local/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6
‹1.28.0 is required
for this version
SciPy (detected version 2.0.2)
warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"|
Traceback (most recent call last):
File "/Accounts/gkanaan/miniconda3/nanomotif/bin/nanomotif"
', line 6, in ‹module >
from nanomotif.main import main
"/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/__init__.py", line in ‹module>
from nanomotif.dataload import *
File "/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/dataload.py", line 3, in ‹module › from .seq import Assembly
File "/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/seq.py", line 1, in ‹module› from scipy.stats import entropy
File "/Accounts/gkanaan/.local/lib/python3.9/site-packages/scipy/stats/__init__.py", line 608, in ‹module › from ._stats_py import *
File "/Accounts/gkanaan/.local/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 39, in ‹module › from scipy.spatial.distance import cdist
File "/Accounts/gkanaan/.local/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 110, in ‹module› from ._kdtree import *
File "/Accounts/gkanaan/.local/lib/python3.9/site-packages/scipy/spatial/_kdtree.py", line 4, in ‹module > from ._ckdtree import cKDTree, cKDTreeNode
File "
_ckdtree.pyx", line 1, in init scipy.spatial._ckdtree
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header,
got 88 from PyObject
```

**Comment by Ge0rges** [comment]
This is fixed by doing `conda install numpy==1.26.4` but then I get:

```
WARNING: root:Output directory nanomotif_install_check already exists
Traceback (most recent call last):
File "/Accounts/gkanaan/miniconda3/nanomotif/bin/nanomotif", line 10,
in <module >
sys. exit(main())
File
"/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/main.py", line 525, in main
shared_setup(args, args.out)
File "/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/main.py", line 42,
in shared_setup
nm.seed.set_seed(args.seed)
File "/Accounts/gkanaan/miniconda3/nanomotif/lib/python3.9/site-packages/nanomotif/seed.py", line 9, in set_seed
pl.set_random_seed (seed)
AttributeError: module 'polars' has no attribute 'set_random_seed`
```

**Comment by Ge0rges** [comment]
Clean install doing `pip install nanomotif` works

**Comment by SorenHeidelbach** [comment]
What is the output of conda list?

**Comment by Ge0rges** [comment]
Sorry I modified the conda environment and can't reproduce this.
